### ISSUE TITLE
Misleading known issue

### ISSUE THREAD

**Issue by pasinskim** [felixge/tcpkeepalive#6] opened 2017-02-01 09:18 UTC
I have noticed known issue mentioned in README file. Is this still the case as I can see the following commits fixing it:
https://github.com/felixge/tcpkeepalive/commit/387b9d2ab4a343ea8892b72339108e6dd78da332
https://github.com/felixge/tcpkeepalive/commit/59d8c3fa70af5275eaacfb5c91364786bf41947e

**Comment by felixge** [comment] 2017-02-02 11:08
The problem is only fixed in the new `SetKeepAlive` func. The old interface is still buggy. See: https://github.com/felixge/tcpkeepalive/issues/3

**Closed by felixge** 2017-02-02 11:08 UTC
